name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install dependencies
        run: npm install

      - name: Build the app
        env:
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_GEMINI_SYSTEM_INSTRUCTIONS: ${{ secrets.NEXT_PUBLIC_GEMINI_SYSTEM_INSTRUCTIONS }}
          NEXT_PUBLIC_AZ104_LOGO: ${{ vars.NEXT_PUBLIC_AZ104_LOGO }}
          NEXT_PUBLIC_AZ900_LOGO: ${{ vars.NEXT_PUBLIC_AZ900_LOGO }}
          NEXT_PUBLIC_MEMOJI_ICON: ${{ vars.NEXT_PUBLIC_MEMOJI_ICON }}
          NEXT_PUBLIC_PROTEXXA_LOGO: ${{ vars.NEXT_PUBLIC_PROTEXXA_LOGO }}
          NEXT_PUBLIC_SECURITYPLUS_LOGO: ${{ vars.NEXT_PUBLIC_SECURITYPLUS_LOGO }}
          NEXT_PUBLIC_ZELYXAI_LOGO: ${{ vars.NEXT_PUBLIC_ZELYXAI_LOGO }}
        run: npm run build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_STONE_0AD0DBE0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/" # App source code path (update if necessary)
          api_location: "" # Api source code path - optional
          output_location: ".next" # Built app content directory for Next.js
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_STONE_0AD0DBE0F }}
          action: "close"
